import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Anchor,
  AppWindow,
  Archive,
  ArrowRight,
  ArrowUpRight,
  BellRing,
  Bluetooth,
  Cable,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  Cpu,
  Download,
  Eye,
  File,
  FileCog,
  FileDown,
  FileText,
  FileUp,
  Fingerprint,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPlus,
  FolderUp,
  Gauge,
  HardDrive,
  History,
  IdCard,
  Info,
  Keyboard,
  ClipboardPaste,
  KeyRound,
  LayoutGrid,
  Library,
  List,
  Maximize2,
  Monitor,
  Move,
  Music,
  Nfc,
  Package,
  Palette,
  Pause,
  Pencil,
  Play,
  Plug,
  Power,
  RadioTower,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Settings,
  Sparkles,
  SquareCheck,
  SquareTerminal,
  TextCursorInput,
  Trash2,
  TvMinimal,
  Undo2,
  Upload,
  Usb,
  Video,
  X,
  Zap,
  Star,
  Tag,
} from "lucide-react";

export const ICONS = {
  anchor: Anchor,
  monitor: Monitor,
  apps: LayoutGrid,
  library: Library,
  folder: Folder,
  cpu: Cpu,
  terminal: SquareTerminal,
  settings: Settings,
  search: Search,
  camera: Camera,
  record: Video,
  archive: Archive,
  clock: History,
  power: Power,
  bell: BellRing,
  refresh: RefreshCw,
  plus: FolderPlus,
  upload: Upload,
  install: Download,
  copy: Copy,
  trash: Trash2,
  check: Check,
  file: File,
  bluetooth: Bluetooth,
  usb: Usb,
  subghz: RadioTower,
  ir: TvMinimal,
  nfc: Nfc,
  rfid: IdCard,
  ibutton: KeyRound,
  gpio: Cable,
  u2f: Fingerprint,
  zap: Zap,
  activity: Activity,
  "hard-drive": HardDrive,
  pencil: Pencil,
  "arrow-up-right": ArrowUpRight,
  "arrow-right": ArrowRight,
  plug: Plug,
  info: Info,
  keyboard: Keyboard,
  clipboard: ClipboardPaste,
  play: Play,
  pause: Pause,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  undo: Undo2,
  "maximize-2": Maximize2,
  "folder-up": FolderUp,
  "folder-open": FolderOpen,
  "folder-input": FolderInput,
  move: Move,
  x: X,
  list: List,
  "square-check": SquareCheck,
  "file-text": FileText,
  "app-window": AppWindow,
  music: Music,
  "file-cog": FileCog,
  package: Package,
  "text-cursor-input": TextCursorInput,
  save: Save,
  palette: Palette,
  gauge: Gauge,
  sparkles: Sparkles,
  "file-down": FileDown,
  "file-up": FileUp,
  "rotate-ccw": RotateCcw,
  eye: Eye,
  star: Star,
  tag: Tag,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
